version: '3.8'

services:
  db:
    image: postgres:16
    container_name: archive_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archive
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data
    ports:
      - "5433:5432"

